version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./flask-python-backend:/app
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    healthcheck:
      test: "exit 0"
      timeout: 30s
  frontend:
    image: node:14
    working_dir: /app
    volumes:
      - ./vue-frontend:/app
    ports:
      - 8080:8080
    command: npm run serve
    depends_on:
      - db
